title: Making an in-app voice call
description: You make a voice call from an Android app to a phone.
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to use make a phone call from an Android app to phone using the Android Client SDK and Java.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an Android application using Kotlin and the Nexmo Android Client SDK, and then write the code to make a phone call from your Android app to a phone.

    Two parts are needed to achieve this:

    * An Android application that will make the voice call using the Client SDK.
    * A publicly accessible URL that serves instructions on how to handle the call. To accomplish this, you will create a webhook server using <a href="https://nodejs.org/en/" target="_blank">Node.js</a>, <a href="https://expressjs.com/" target="_blank">Express</a> and <a href="https://github.com/localtunnel/localtunnel" target="_blank">localtunnel</a>.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-phone-java](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-phone-java) folder.

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli-beta
  - install-android-studio

tasks:
  - client-sdk/app-to-phone/create-webhook-server
  - client-sdk/app-to-phone/create-application
  - client-sdk/create-user-alice
  - client-sdk/generate-jwt-alice
  - client-sdk/app-to-phone/create-project
  - client-sdk/app-to-phone/add-permissions
  - client-sdk/app-to-phone/main-screen
  - client-sdk/app-to-phone/client
  - client-sdk/app-to-phone/place-call
  - client-sdk/app-to-phone/end-call

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    The complete version of the project you just built is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-phone-java](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-phone-java) folder.

    You can do a lot more with the Client SDK. See [Client SDK documentation](/client-sdk/overview) or review
    [Android Client SDK documentation](/sdk/stitch/android/index).

    We want to hear what ideas you have in mind? Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>

    
