title: Making an in-app voice call
description: You make a voice call from an Android app to a phone.
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to use make a phone call from an Android app to phone using the Android Client SDK and Kotlin.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an Android application using Kotlin and the Nexmo Android Client SDK, and then write the code to make a phone call from your Android app to a phone.
    The source code is available on [GitHub](https://github.com/nexmo-community/client-sdk-android-tutorial-voice-app-to-phone).

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli-beta
  - install-android-studio

tasks:
  - client-sdk/app-to-phone/create-ncco
  - client-sdk/android-shared/create-application
  - client-sdk/android-shared/call/create-user-alice
  - client-sdk/android-shared/generate-jwt-alice
  - client-sdk/app-to-phone/starter-project
  - client-sdk/android-shared/initialize-client
  - client-sdk/android-shared/configure-jwt-alice
  - client-sdk/android-shared/call/authenticate-alice
  - client-sdk/app-to-phone/make-call

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For the complete version please see the Android Studio project in the `kotlin-completed` folder of 
    the [git repository](https://github.com/nexmo-community/client-sdk-android-tutorial-voice-app-to-phone) you've cloned.

    You can do a lot more with the Client SDK. See [Client SDK documentation](/client-sdk/overview) or review
    [Android Client SDK documentation](/sdk/stitch/android/index).

    We want to hear what ideas you have in mind? Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>

    
