title: Making an in-app voice call
description: Make a voice call from a web app to a phone using the Android Client SDK.
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to use make a phone call from an Android app to phone using the Android Client SDK and Kotlin.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an Android application using Kotlin and the Nexmo Android Client SDK, and then write the code to make a phone call from your Android app to a phone.
    The source code is available on [GitHub](https://github.com/nexmo-community/client-sdk-android-tutorial-voice-app-to-phone-kotlin).

    This tutorial uses NexmoClient version 2.x

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli-beta
  - install-android-studio
  - join-github

tasks:
  - client-sdk/app-to-phone/create-ncco
  - client-sdk/app-to-phone/create-application
  - client-sdk/android-shared/create-user-alice
  - client-sdk/android-shared/generate-jwt-alice
  - client-sdk/app-to-phone/create-project
  - client-sdk/android-shared/add-dependencies
  - client-sdk/app-to-phone/create-screens
  - client-sdk/app-to-phone/setup-navigation
  - client-sdk/app-to-phone/add-permissions
  - client-sdk/app-to-phone/configure-jwt
  - client-sdk/android-shared/initialize-client
  - client-sdk/app-to-phone/authenticate-alice
  - client-sdk/app-to-phone/main-screen
  - client-sdk/app-to-phone/build-on-call-screen
  - client-sdk/android-shared/run-app

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For the complete version please see the Android Studio project in the `kotlin-completed` folder of 
    the [git repository](https://github.com/nexmo-community/client-sdk-android-tutorial-voice-app-to-phone-kotlin) you've cloned.

    You can do a lot more with the Client SDK. See [Client SDK documentation](/client-sdk/overview) or review
    [Android Client SDK documentation](/sdk/stitch/android/index).

    We want to hear what ideas you have in mind? Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>

    
