title: Making an in-app voice call
description: You make a voice call from an iOS app to a phone.
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to use make a phone call from an iOS app using the iOS Client SDK and Objective-C.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an iOS application using Objective-C and the Nexmo iOS Client SDK, and then write the code to make a phone call from your iOS app to a phone.

    Two parts are needed to achieve this:

    * An iOS application that will make the voice call using the Client SDK.
    * A publicly accessible URL that serves instructions on how to handle the call. To accomplish this, you will create a webhook server using <a href="https://nodejs.org/en/" target="_blank">Node.js</a>, <a href="https://expressjs.com/" target="_blank">Express</a> and <a href="https://github.com/localtunnel/localtunnel" target="_blank">localtunnel</a>.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-phone-objc](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-phone-objc) folder.

    *This tutorial uses NexmoClient version 3.0.0*


prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta
- buy-nexmo-number
- link-nexmo-number
- install-xcode

tasks:
- client-sdk/app-to-phone/create-webhook-server
- client-sdk/app-to-phone/create-application
- client-sdk/create-user-alice
- client-sdk/generate-jwt-alice
- client-sdk/app-to-phone/create-project
- client-sdk/app-to-phone/add-permissions
- client-sdk/app-to-phone/main-screen
- client-sdk/app-to-phone/client
- client-sdk/app-to-phone/place-call

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For completeness, the project you've built as part of this tutorial is also available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-phone-objc](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-phone-objc) folder.

    You can do a lot more with the Client SDK. For an summary, please see the [Client SDK Overview](/client-sdk/overview) or review the [iOS Client SDK documentation](/client-sdk/sdk-documentation/ios).

    We want to hear what ideas you have in mind! Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)
