title: Creating an Android chat app
description: Create a Android application that enables users to message each other using the Android Client SDK and Java.
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to create a Android chat application using the Android Client SDK and Java.
  content: |
    # Introduction
    In this task, you will learn how to create and configure a Client SDK Application and then code an application that enables two users to send messages to each other.

    First, you will create a Conversation and two Users. Then, you will authenticate these Users and add them to the Conversation as Members.

    Finally, you will implement chat functionality in your application, including the ability to view and send messages and be notified when a new message appears in Conversation.

    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [in-app-messaging-java](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/in-app-messaging-java) folder.

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli
  - install-vonage-cli-conversations
  - install-android-studio

tasks:

  - client-sdk/in-app-messaging/create-application
  - client-sdk/create-conversation
  - client-sdk/create-users-alice-and-bob
  - client-sdk/in-app-messaging/add-users-to-conversation
  - client-sdk/generate-jwts-alice-and-bob
  - client-sdk/in-app-messaging/create-project
  - client-sdk/in-app-messaging/add-permissions
  - client-sdk/in-app-messaging/main-screen
  - client-sdk/in-app-messaging/initialize-client
  - client-sdk/in-app-messaging/fetch-conversation
  - client-sdk/in-app-messaging/fetch-events
  - client-sdk/in-app-messaging/send-message
  - client-sdk/in-app-messaging/receive-new-messages

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For the complete version please see the Android Studio project on [GitHub](https://github.com/nexmo-community/client-sdk-android-tutorial-messaging-java).

    You can do a lot more with the Client SDK:
    
    - to enable audio read this [guide](/client-sdk/in-app-voice/guides/enable-audio/java)
    - read the [Client SDK documentation](/client-sdk/overview)
    - review the [Android Client SDK documentation](/sdk/stitch/android/index)
    - try the [Client SDK Android Samples](https://github.com/nexmo-community/client-sdk-android-samples) repository

    We want to hear what ideas you have in mind! Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>.
