title: Receiving a phone call in-app
description: You receive a call from a phone to your app
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to handle an inbound call into your web app using the JavaScript Client SDK.
  content: |
    # Introduction
    In this tutorial, you will learn how to create a Client SDK application and then write the code to receive an
    inbound <abbr title="Public Switched Telephone Network">PSTN</abbr> call.

    To achieve this, you will need:

    * A web application that will notify the service agent of an inbound call and offer the ability to answer it.
    * A webhook server that can process an inbound webhook and return an <abbr title="Nexmo Call Control Object">NCCO</abbr> to forward the inbound call to your application using [Node.js](https://nodejs.org/en/), [Express](https://expressjs.com/), and [localtunnel](https://github.com/localtunnel/localtunnel).

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [phone-to-app-js](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/phone-to-app-js) folder.

prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta

tasks:
- client-sdk/phone-to-app/create-webhook-server
- client-sdk/phone-to-app/create-application
- buy-nexmo-number
- link-nexmo-number
- client-sdk/create-user-alice
- client-sdk/generate-jwt-alice
- client-sdk/phone-to-app/main-screen
- client-sdk/phone-to-app/receive-call

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    The complete version of the project you just built is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) - please see the [phone-to-app-js](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/phone-to-app-js) folder.

    You can do a lot more with the Client SDK. For an summary, please see the [Client SDK Overview](/client-sdk/overview) or review the [JS Client SDK documentation](/sdk/stitch/javascript/index).

    We want to hear what ideas you have in mind! Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)

    See [Client SDK documentation](/client-sdk/overview).
