title: Recieving a phone call in-app
description: You recieve a call from a phone to your app
products: 
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to handle an inbound call into your web app using the iOS Client SDK.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an iOS application using Swift and the Client SDK, and then write the code to receive an
    inbound <abbr title="Public Switched Telephone Network">PSTN</abbr> call.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project for this tutorial is available on [Github]() for you to download.

prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta
- install-xcode
- join-github

tasks:
- client-sdk/phone-to-app/create-ncco
- client-sdk/phone-to-app/create-application
- buy-nexmo-number
- link-nexmo-number
- client-sdk/create-user
- client-sdk/generate-jwt-alice
- client-sdk/phone-to-app/swift-project
- client-sdk/phone-to-app/swift-permissions
- client-sdk/phone-to-app/swift-interface
- client-sdk/phone-to-app/swift-client
- client-sdk/phone-to-app/swift-call


conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For completeness, the project you've built as part of this tutorial is also available on [Github]().

    And... you can do a lot more with the Client SDK,  see [Client SDK documentation](/client-sdk/overview).

    We want to hear what ideas you have in mind? Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)

   