name: Vonage API Developer
subtitle: Nexmo is now Vonage
base_url: 'https://developer.nexmo.com'
docs_repo: 'nexmo/nexmo-developer'
oas_url: https://www.github.com/nexmo/api-specification/blob/master/definitions
header:
  links:
    sign-up:
      path: https://dashboard.nexmo.com/sign-up?icid=tryitfree_api-developer-adp_nexmodashbdfreetrialsignup_nav
      text:
        - try-it
        - get_an_api_key
        - start_building
    sign-in:
      path: https://dashboard.nexmo.com/sign-in?icid=nexmocustomer_api-developer-adp_nexmodashbdsigin_nav
      text: sign-in
code_snippets:
  - title: 'Send an SMS'
    source: '_examples/messaging/sms/send-an-sms'
  - title: 'Make a voice call'
    source: '_examples/voice/make-an-outbound-call'
  - title: 'Send a WhatsApp message'
    source: '_examples/messages/whatsapp/send-text'

footer:
  links:
    status:
      path: 'https://www.nexmostatus.com/'
      text: 'API Status'
    navigation:
      documentation:
        - documentation: 'https://developer.nexmo.com/documentation'
        - vonage-business-cloud: 'https://developer.uc.vonage.com/'
        - vonage-contact-center: 'https://developer.newvoicemedia.com/'
      technical-references:
        - documentation: 'https://developer.nexmo.com/documentation'
        - use-cases: 'https://developer.nexmo.com/use-cases'
        - sdk-&-tools: 'https://developer.nexmo.com/tools'
        - integrations: 'https://developer.nexmo.com/extend'
      community:
        - community-hub: 'https://developer.nexmo.com/community'
        - startups-program: 'https://developer.nexmo.com/startups'
        - voyagers-program: 'https://developer.nexmo.com/voyagers'
        - careers: 'https://developer.nexmo.com/careers'
    support:
      knowledgebase: 'https://help.nexmo.com/'
      known-issues: 'https://help.nexmo.com/hc/en-us/sections/115004147507'
      changelog: 'https://changelog.nexmo.com/'
    social:
      linkedin: 'https://www.linkedin.com/company/vonage/'
      twitter: 'https://twitter.com/vonagedev'
      slack: 'https://developer.vonage.com/slack'
      github: 'https://github.com/vonage'
      stackoverflow: 'http://stackoverflow.com/questions/tagged/vonage'
