name: Vonage API Developer
subtitle: Nexmo is now Vonage
base_url: 'https://developer.nexmo.com'
docs_repo: 'nexmo/nexmo-developer'
oas_url: https://www.github.com/nexmo/api-specification/blob/master/definitions
header:
  links:
    sign-up:
      path: https://dashboard.nexmo.com/sign-up?icid=tryitfree_api-developer-adp_nexmodashbdfreetrialsignup_nav
      text:
        - try-it
        - get_an_api_key
        - start_building
    sign-in:
      path: https://identity.nexmo.com/login?icid=nexmocustomer_api-developer-adp_nexmodashbdsigin_nav
      text: sign-in
code_snippets:
  - title: 'Send an SMS'
    source: '_examples/messaging/sms/send-an-sms'
  - title: 'Make a voice call'
    source: '_examples/voice/make-an-outbound-call'
  - title: 'Send a WhatsApp message'
    source: '_examples/messages/whatsapp/send-text'

footer:
  links:
    status:
      path: 'https://api.vonagestatus.com/'
      text: 'API Status'
    navigation:
      documentation:
        - documentation: '/documentation'
        - vonage-business-cloud: 'https://developer.uc.vonage.com/'
        - vonage-contact-center: 'https://developer.newvoicemedia.com/'
      technical-references:
        - documentation: '/documentation'
        - use-cases: '/use-cases'
        - sdk-&-tools: '/tools'
        - integrations: '/extend'
      community:
        - community-hub: '/community'
        - startups-program: '/startups'
        - team: '/team'
        - careers: '/careers'
    support:
      knowledgebase: 'https://api.support.vonage.com/'
      known-issues: 'https://api.support.vonage.com/hc/en-us/sections/115004147507'
      changelog: '/changelogs'
    social:
      linkedin: 'https://www.linkedin.com/company/vonage/'
      twitter: 'https://twitter.com/vonagedev'
      slack: '/slack'
      github: 'https://github.com/vonage'
      stackoverflow: 'http://stackoverflow.com/questions/tagged/vonage'
