current:
  - name: 'Adam Culp'
    email: 'adam.culp@vonage.com'
    twitter: 'adamculp'
  - name: 'Kelly Andrews'
    email: 'kelly.andrews@vonage.com'
    twitter: 'kellyjandrews'
  - name: 'Lorna Mitchell'
    email: 'lorna.mitchell@vonage.com'
    twitter: 'lornajane'
  - name: 'Martyn Davies'
    email: 'martyn.davies@vonage.com'
    twitter: 'martynd'
    role: 'Head of Developer Education'
  - name: 'Michael Heap'
    email: 'michael.heap@vonage.com'
    twitter: 'mheap'
    role: 'Head of Platform Experience'
  - name: 'Nahrin Jalal'
    email: 'nahrin.jalal@vonage.com'
    twitter: 'NahrinJalal'
    role: 'Developer Educator'
  - name: 'Olia Dukova'
    email: 'olia.dukova@vonage.com'
    twitter: 'oliadukova'
    role: 'Global Head of Community'
  - name: 'Tony Bedford'
    email: 'tony.bedford@vonage.com'
    role: 'Technical Writer'
  - name: 'Myrsini Koukiasa'
    email: 'myrsini.koukiasa@vonage.com'
    twitter: 'myrsiningos'
    role: 'Senior Community Manager'
  - name: 'Garann Means'
    email: 'garann.means@vonage.com'
  - name: 'Ben Greenberg'
    email: 'ben.greenberg@vonage.com'
    twitter: 'rabbigreenberg'
  - name: 'Paul Ardeleanu'
    email: 'paul.ardeleanu@vonage.com'
    twitter: 'pardel'
  - name: 'Luke Oliff'
    email: 'luke.oliff@vonage.com'
    twitter: 'mroliff'
  - name: 'Fabian Rodriguez'
    email: 'fabian.rodriguez@vonage.com'
    twitter: 'fabianrbz'
    role: 'Nexmo Developer Tech Lead'
  - name: 'Lauren Lee'
    email: 'lauren.lee@vonage.com'
    twitter: 'lolocoding'
    role: 'Developer Educator'
  - name: 'Laura Czajkowski'
    email: 'laura.czajkowski@vonage.com'
    twitter: 'Czajkowski'
    role: 'Developer Relations Manager'
  - name: 'Bethany Loft'
    email: 'bethany.loft@vonage.com'
    twitter: 'bb_loft'
    role: 'Junior Community Event Manager'
  - name: 'Steve Lorello'
    email: 'steve.lorello@vonage.com'
    twitter: 'slorello'
  - name: 'Chris Tankersley'
    email: 'chris.tankersley@vonage.com'
    twitter: 'dragonmantank'
  - name: 'Dwane Hemmings'
    email: 'dwane.hemmings@vonage.com'
    twitter: 'dwaneio'
  - name: 'Michael Jolley'
    email: 'michael.jolley@vonage.com'
    twitter: 'michaeljolley'
  - name: 'Nick Iati'
    email: 'nick.iati@vonage.com'
    role: 'Technical Writer'
  - name: 'Kevin Lewis'
    email: 'kevin.lewis@vonage.com'
  - name: 'Benjamin Aronov'
    email: 'benjamin.aronov@vonage.com'
    role: 'Online Community Manager'
  - name: "Diana Rodriguez"
    email: "diana.rodriguezmanrique@vonage.com"
    twitter: "cotufa82"
  - name: "Greg Holmes"
    email: "greg.holmes2@vonage.com"
    role: "Developer Educator"
    twitter: "greg__holmes"
  - name: "Igor Wojda"
    email: "igor.wojda@vonage.com"
    twitter: "igorwojda"
  - name: "Yvonne Allen"
    email: "yvonne.allen@vonage.com"
    twitter: "yallen011"
  - name: "Abdul Ajetunmobi"
    email: "abdul.ajetunmobi@vonage.com"
    twitter: "abdulajet"
  - name: "Clarisse Ng"
    email: "clarisse.ng@vonage.com"
    role: "Community Manager, APAC"
  - name: "Avital Tzubeli"
    email: "avital.tzubeli@vonage.com"
    role: "Regional Developer Advocate"
