---
title: Play Audio into a WebSocket
description: Learn how to connect an inbound Voice API call to a WebSocket, then play audio with JavaScript.
products:
  - voice/voice-api

introduction: 
  title: Introduction to this task
  description: This task shows you how to use the Voice API 
  content: |
    # Introduction

    You can use the Vonage Voice API to connect a call to a [WebSocket](/voice/voice-api/guides/websockets), giving you a two-way stream of the call audio delivered over the WebSocket protocol in real-time. This enables you to process the call audio to perform tasks such as sentiment analysis, real-time transcription and decision-making using artificial intelligence.

    In this tutorial, you will connect an inbound call to a WebSocket endpoint. The WebSocket server will stream an audio file into the call. You will implement this using the [express](https://expressjs.com) web application framework and [express-ws](https://www.npmjs.com/package/express-ws), which lets you define WebSocket endpoints like any other `express` route.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/voice-api-web-socket-audio).

prerequisites:
  - create-nexmo-account
  - install-nexmo-cli
tasks:
  - buy-nexmo-number
  - voice/voice-api/call-a-websocket/create-voice-application
  - link-nexmo-number
  - voice/voice-api/play-audio-websocket/create-the-project
  - voice/voice-api/play-audio-websocket/write-answer-webhook
  - voice/voice-api/call-a-websocket/write-event-webhook
  - voice/voice-api/play-audio-websocket/create-the-websocket
  - voice/voice-api/play-audio-websocket/test-your-application

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    The complete version of the project you just built is available on [Github](https://github.com/nexmo-community/voice-api-web-socket-audio).

    The following resources will help you learn more about using WebSockets in your Voice API applications:

    * The [WebSockets guide](/voice/voice-api/guides/websockets)
    * The [WebSocket protocol standard](https://tools.ietf.org/html/rfc6455)
    * The [Getting Started with Vonage Voice and WebSockets recorded webinar](https://www.nexmo.com/blog/2017/02/15/webinar-getting-started-nexmo-voice-websockets-dr/)
    * [Articles about WebSockets](https://www.nexmo.com/?s=websockets) on the Vonage Developer Blog
    * The [NCCO connect action](/voice/voice-api/ncco-reference#connect)
    * The [Endpoints guide](/voice/voice-api/guides/endpoints)
    * The [Voice API reference documentation](/voice/voice-api/api-reference)

    We want to hear what ideas you have in mind? Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>

