---
title: Play Audio into a Call with Ruby
products:
 - voice/voice-api
description: A tutorial showing you how to build an app that will play audio into a PSTN call
languages:
 - ruby

introduction:
  title: Introduction to this tutorial
  description: This tutorial shows you how to play audio into a phone call using Ruby
  content: |
    # Introduction
    The [Vonage Voice API](/voice/voice-api/overview) is the easiest way to build high-quality voice applications in the Cloud. In this tutorial you will learn how to stream pre-recorded audio into both inbound and outbound calls using Ruby and the Vonage Voice API.

    This tutorial provides step by step instructions showing you how to:

    1. Set up a Vonage account
    1. Create a Vonage Application
    1. Configure a Vonage Application 
    1. Create an Sinatra application
    1. Add the Vonage Ruby SDK to it
    1. Receive a call and play audio into it
    1. Place a call and stream audio into it

prerequisites:
  - create-nexmo-account
  - install-nexmo-cli
  - run-ngrok
  - voice/voice-api/create-vonage-application

tasks:
  - voice/voice-api/play-audio-ruby/create-voice-rubyproj
  - voice/voice-api/install-vonage-ruby
  - voice/voice-api/play-audio-ruby/require-dependencies
  - voice/voice-api/play-audio-ruby/initialize-vonage-client
  - voice/voice-api/play-audio-ruby/add-env-variables
  - voice/voice-api/play-audio-ruby/define-constants
  - voice/voice-api/play-audio-ruby/create-routes
  - voice/voice-api/play-audio-ruby/run-app

conclusion:
  title: What's Next?
  content: |
    # What's Next?

    Find out more about the capabilities of the Vonage Voice API:

    - [Read the Voice API documentation](/voice/voice-api/overview)
    - [View the API Reference](https://developer.nexmo.com/voice/voice-api/api-reference)
    - [Play Text To Speech into a Call](https://developer.nexmo.com/voice/voice-api/code-snippets/make-an-outbound-call-with-ncco/ruby)
    - [Record a Call](https://developer.nexmo.com/voice/voice-api/code-snippets/record-a-call/ruby)    
    - [Take Speech Input](https://developer.nexmo.com/voice/voice-api/code-snippets/handle-user-input-with-asr/ruby)
    - [Handle User Key Input](https://developer.nexmo.com/voice/voice-api/code-snippets/handle-user-input-with-dtmf)
    - [NCCO Reference](https://developer.nexmo.com/voice/voice-api/ncco-reference)
